{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "09a7dbe6-af3b-440c-8be8-957c60019a7f",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Ans-> 1)When creating a custom exception, it is important to use the Exception class as the base class for your custom exception. \n",
    "2) This is because the Exception class provides a standard interface and set of behaviors that make it easier to work with and catch exceptions.\n",
    "3) Since all exceptions in Python inherit from the Exception class, using it as the base class for your custom exception\n",
    "allows you to catch all exceptions by using the \"except Exception\" statement in a try-except block.\n",
    "4)This can be useful when you want to handle any type of exception in the same way."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f5584ec7-d96c-4c94-9197-b8d17d43a489",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      "InvalidTypeInArgsException\n",
      "UnableToResolveVariableException\n",
      "_Error\n",
      "ResolutionError\n",
      "UnknownExtra\n",
      "DistributionNotFound\n",
      "VersionConflict\n",
      "ContextualVersionConflict\n",
      "RecursiveGrammarException\n",
      "ParseBaseException\n",
      "ParseFatalException\n",
      "ParseSyntaxException\n",
      "ParseException\n",
      "Error\n",
      "Fault\n",
      "ResponseError\n",
      "ProtocolError\n",
      "ExpatError\n",
      "DebuggerInitializationError\n",
      "QueueFull\n",
      "QueueEmpty\n",
      "_Ipv6UnsupportedError\n",
      "Error\n",
      "TimeoutExpired\n",
      "AccessDenied\n",
      "NoSuchProcess\n",
      "ZombieProcess\n",
      "KillEmbedded\n",
      "InteractivelyDefined\n",
      "HTTPException\n",
      "LineTooLong\n",
      "BadStatusLine\n",
      "RemoteDisconnected\n",
      "ImproperConnectionState\n",
      "ResponseNotReady\n",
      "CannotSendHeader\n",
      "CannotSendRequest\n",
      "IncompleteRead\n",
      "UnimplementedFileMode\n",
      "UnknownTransferEncoding\n",
      "UnknownProtocol\n",
      "InvalidURL\n",
      "NotConnected\n",
      "Error\n",
      "MessageError\n",
      "CharsetError\n",
      "MultipartConversionError\n",
      "MessageParseError\n",
      "BoundaryError\n",
      "HeaderParseError\n",
      "InvalidPythonEnvironment\n",
      "OnErrorLeaf\n",
      "_JediError\n",
      "RefactoringError\n",
      "WrongVersion\n",
      "InternalError\n",
      "ParamIssue\n",
      "HasNoContext\n",
      "UncaughtAttributeError\n",
      "SimpleGetItemNotFound\n",
      "_PositionUpdatingFinished\n",
      "InternalParseError\n",
      "ParserSyntaxError\n",
      "HeightIsUnknownError\n",
      "InvalidLayoutError\n",
      "_Retry\n",
      "EditReadOnlyBuffer\n",
      "ValidationError\n",
      "DOMException\n",
      "ValidationErr\n",
      "InvalidAccessErr\n",
      "NamespaceErr\n",
      "InvalidModificationErr\n",
      "SyntaxErr\n",
      "InvalidStateErr\n",
      "InuseAttributeErr\n",
      "NotSupportedErr\n",
      "NotFoundErr\n",
      "NoModificationAllowedErr\n",
      "NoDataAllowedErr\n",
      "InvalidCharacterErr\n",
      "WrongDocumentErr\n",
      "HierarchyRequestErr\n",
      "DomstringSizeErr\n",
      "IndexSizeErr\n",
      "SpaceInInput\n",
      "Warning\n",
      "Error\n",
      "DatabaseError\n",
      "NotSupportedError\n",
      "DataError\n",
      "IntegrityError\n",
      "ProgrammingError\n",
      "OperationalError\n",
      "InternalError\n",
      "InterfaceError\n",
      "AliasError\n",
      "InvalidAliasError\n",
      "PrefilterError\n",
      "ErrorToken\n",
      "GetoptError\n",
      "InputRejected\n",
      "IPythonCoreError\n",
      "StdinNotImplementedError\n",
      "UsageError\n",
      "TryNext\n",
      "ProfileDirError\n",
      "HomeDirError\n",
      "FindCmdError\n",
      "PtyProcessError\n",
      "ExceptionPexpect\n",
      "TIMEOUT\n",
      "EOF\n",
      "Restart\n",
      "BdbQuit\n",
      "OptionError\n",
      "CannotEval\n",
      "NotOneValueFound\n",
      "ErrorDuringImport\n",
      "DuplicateKernelError\n",
      "NoSuchEntryPoint\n",
      "BadEntryPoint\n",
      "LargeZipFile\n",
      "BadZipFile\n",
      "NoIPAddresses\n",
      "Error\n",
      "ParsingError\n",
      "MissingSectionHeaderError\n",
      "InterpolationError\n",
      "InterpolationDepthError\n",
      "InterpolationSyntaxError\n",
      "InterpolationMissingOptionError\n",
      "NoOptionError\n",
      "DuplicateOptionError\n",
      "DuplicateSectionError\n",
      "NoSectionError\n",
      "_GiveupOnFastCopy\n",
      "RegistryError\n",
      "LZMAError\n",
      "error\n",
      "InvalidPortNumber\n",
      "Return\n",
      "ReturnValueIgnoredError\n",
      "BadYieldError\n",
      "LeakedCallbackError\n",
      "UnknownKeyError\n",
      "KeyReuseError\n",
      "ReturnValueIgnoredError\n",
      "error\n",
      "TimeoutError\n",
      "error\n",
      "ApplicationError\n",
      "ConfigurableError\n",
      "MultipleInstanceError\n",
      "ConfigError\n",
      "ConfigFileNotFound\n",
      "ConfigLoaderError\n",
      "ArgumentError\n",
      "ArgumentTypeError\n",
      "ArgumentError\n",
      "_Stop\n",
      "PickleError\n",
      "UnpicklingError\n",
      "PicklingError\n",
      "ZMQBaseError\n",
      "NotDone\n",
      "ZMQBindError\n",
      "ZMQError\n",
      "InterruptedSystemCall\n",
      "Again\n",
      "ContextTerminated\n",
      "ArgumentError\n",
      "Full\n",
      "Empty\n",
      "QueueFull\n",
      "QueueEmpty\n",
      "LimitOverrunError\n",
      "InvalidStateError\n",
      "TimeoutError\n",
      "Incomplete\n",
      "error\n",
      "_GiveupOnSendfile\n",
      "Error\n",
      "InvalidStateError\n",
      "TimeoutError\n",
      "CancelledError\n",
      "Error\n",
      "TraitError\n",
      "EndOfBlock\n",
      "ClassFoundException\n",
      "StopTokenizing\n",
      "TokenError\n",
      "SubprocessError\n",
      "TimeoutExpired\n",
      "CalledProcessError\n",
      "Error\n",
      "Verbose\n",
      "error\n",
      "_Error\n",
      "_OptionError\n",
      "Warning\n",
      "PkgResourcesDeprecationWarning\n",
      "DeprecatedTzFormatWarning\n",
      "ResourceWarning\n",
      "BytesWarning\n",
      "UnicodeWarning\n",
      "ImportWarning\n",
      "FutureWarning\n",
      "ProvisionalCompleterWarning\n",
      "RuntimeWarning\n",
      "PEP440Warning\n",
      "UnknownTimezoneWarning\n",
      "ProactorSelectorThreadWarning\n",
      "SyntaxWarning\n",
      "PendingDeprecationWarning\n",
      "DeprecationWarning\n",
      "ProvisionalWarning\n",
      "EncodingWarning\n",
      "UserWarning\n",
      "FormatterWarning\n",
      "GetPassWarning\n",
      "BufferError\n",
      "MemoryError\n",
      "ReferenceError\n",
      "SystemError\n",
      "CodecRegistryError\n",
      "ArithmeticError\n",
      "DecimalException\n",
      "InvalidOperation\n",
      "InvalidContext\n",
      "DivisionUndefined\n",
      "DivisionImpossible\n",
      "ConversionSyntax\n",
      "FloatOperation\n",
      "DivisionByZero\n",
      "Subnormal\n",
      "Underflow\n",
      "Inexact\n",
      "Overflow\n",
      "Underflow\n",
      "Rounded\n",
      "Overflow\n",
      "Underflow\n",
      "Clamped\n",
      "ZeroDivisionError\n",
      "DivisionUndefined\n",
      "DivisionByZero\n",
      "OverflowError\n",
      "FloatingPointError\n",
      "AssertionError\n",
      "ValueError\n",
      "InvalidVersion\n",
      "InvalidRequirement\n",
      "RequirementParseError\n",
      "UndefinedEnvironmentName\n",
      "UndefinedComparison\n",
      "InvalidMarker\n",
      "InvalidSpecifier\n",
      "InvalidSdistFilename\n",
      "InvalidWheelFilename\n",
      "_InvalidELFFileHeader\n",
      "InvalidVersion\n",
      "UnequalIterablesError\n",
      "InvalidFileException\n",
      "MacroToEdit\n",
      "MessageDefect\n",
      "HeaderDefect\n",
      "InvalidDateDefect\n",
      "NonASCIILocalPartDefect\n",
      "ObsoleteHeaderDefect\n",
      "NonPrintableDefect\n",
      "HeaderMissingRequiredValue\n",
      "InvalidHeaderDefect\n",
      "InvalidBase64LengthDefect\n",
      "InvalidBase64CharactersDefect\n",
      "InvalidBase64PaddingDefect\n",
      "UndecodableBytesDefect\n",
      "InvalidMultipartContentTransferEncodingDefect\n",
      "MultipartInvariantViolationDefect\n",
      "MissingHeaderBodySeparatorDefect\n",
      "MisplacedEnvelopeHeaderDefect\n",
      "FirstHeaderLineIsContinuationDefect\n",
      "CloseBoundaryNotFoundDefect\n",
      "StartBoundaryNotFoundDefect\n",
      "NoBoundaryInMultipartDefect\n",
      "ClipboardEmpty\n",
      "ClassNotFound\n",
      "ParserError\n",
      "IllegalWeekdayError\n",
      "IllegalMonthError\n",
      "UnsupportedDigestmodError\n",
      "Error\n",
      "SSLCertVerificationError\n",
      "JSONDecodeError\n",
      "UnsupportedOperation\n",
      "UnicodeError\n",
      "UnicodeTranslateError\n",
      "UnicodeDecodeError\n",
      "UnicodeEncodeError\n",
      "LookupError\n",
      "CodecRegistryError\n",
      "KeyError\n",
      "UnknownBackend\n",
      "NoSuchKernel\n",
      "IndexError\n",
      "SyntaxError\n",
      "IndentationError\n",
      "TabError\n",
      "AttributeError\n",
      "FrozenInstanceError\n",
      "NameError\n",
      "UnboundLocalError\n",
      "RuntimeError\n",
      "VariableError\n",
      "ExtractionError\n",
      "SendfileNotAvailableError\n",
      "BrokenExecutor\n",
      "BrokenThreadPool\n",
      "BrokenBarrierError\n",
      "_DeadlockError\n",
      "NotImplementedError\n",
      "StdinNotImplementedError\n",
      "ZMQVersionError\n",
      "RecursionError\n",
      "EOFError\n",
      "IncompleteReadError\n",
      "OSError\n",
      "BadGzipFile\n",
      "URLError\n",
      "ContentTooShortError\n",
      "HTTPError\n",
      "ReadError\n",
      "ExecError\n",
      "SpecialFileError\n",
      "Error\n",
      "SameFileError\n",
      "SSLError\n",
      "SSLEOFError\n",
      "SSLSyscallError\n",
      "SSLWantReadError\n",
      "SSLWantWriteError\n",
      "SSLZeroReturnError\n",
      "SSLCertVerificationError\n",
      "gaierror\n",
      "herror\n",
      "itimer_error\n",
      "UnsupportedOperation\n",
      "TimeoutError\n",
      "ProcessLookupError\n",
      "PermissionError\n",
      "InterruptedError\n",
      "InterruptedSystemCall\n",
      "NotADirectoryError\n",
      "IsADirectoryError\n",
      "FileNotFoundError\n",
      "FileExistsError\n",
      "ChildProcessError\n",
      "BlockingIOError\n",
      "ConnectionError\n",
      "ConnectionResetError\n",
      "RemoteDisconnected\n",
      "ConnectionRefusedError\n",
      "ConnectionAbortedError\n",
      "BrokenPipeError\n",
      "ImportError\n",
      "ZipImportError\n",
      "ModuleNotFoundError\n",
      "StopIteration\n",
      "StopAsyncIteration\n",
      "TypeError\n",
      "MultipartConversionError\n",
      "FloatOperation\n"
     ]
    }
   ],
   "source": [
    "# Q2. Write a python program to print Python Exception Hierarchy.\n",
    "import logging\n",
    "logging.basicConfig(filename = '13Feb2.log',level =logging.INFO)\n",
    "logging.info('This program is written for printing exception hierarchy.')\n",
    "a = [Exception]\n",
    "while a:\n",
    "    b = a.pop()\n",
    "    print(b.__name__)\n",
    "    c = b.__subclasses__()\n",
    "    for i in c:\n",
    "        if i not in a:\n",
    "            a.append(i)\n",
    "\n",
    "# def print_exception_hierarchy():\n",
    "#     base_exception = Exception\n",
    "#     exceptions = [base_exception]\n",
    "#     while exceptions:\n",
    "#         current_exception = exceptions.pop()\n",
    "#         print(current_exception.__name__)\n",
    "#         sub_exceptions = current_exception.__subclasses__()\n",
    "#         for sub_exception in sub_exceptions:\n",
    "#             if sub_exception not in exceptions:\n",
    "#                 exceptions.append(sub_exception)\n",
    "\n",
    "# print_exception_hierarchy()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "714b1354-4ef0-4c34-9342-701f95c51f14",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Value error has been handled\n"
     ]
    }
   ],
   "source": [
    "# Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "# Ans->The ArithmeticError class is a built-in class in Python that is used to represent errors that occur during arithmetic operations. \n",
    "# This class is a subclass of the Exception class and is used to handle errors that are related to arithmetic operations such as\n",
    "# division by zero, overflow errors, and other related issues.\n",
    "# example 1: ValueError \n",
    "import logging\n",
    "import math\n",
    "logging.basicConfig(filename='13Feb2.log',level = logging.info)\n",
    "try:\n",
    "    x = -5\n",
    "    y = math.sqrt(x)  \n",
    "except ValueError :\n",
    "    logging.error('This Value error has arrived')\n",
    "    print('Value error has been handled')\n",
    "except Exception as e:\n",
    "    logging.error(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "038cd706-c513-4446-9286-1c992f21cf3d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Zero division error has been handled\n"
     ]
    }
   ],
   "source": [
    "# Example 2- ZerodivisionError\n",
    "try:    \n",
    "    a = 1\n",
    "    b = 0\n",
    "    c = a/b\n",
    "except ZeroDivisionError:\n",
    "    logging.error('Zero division error has been handled')\n",
    "    print('Zero division error has been handled')\n",
    "except Exception as e:\n",
    "    logging.error(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "36620d48-1295-4082-b498-b0765ebbd2c2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Key error has been handled.\n"
     ]
    }
   ],
   "source": [
    "# Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "# Ans->a) The LookupError class is used to represent errors that occur when an invalid key or index is used to access \n",
    "# a value in a sequence or mapping object.\n",
    "# b) This class is used to handle errors that are related to lookup operations such as indexing, slicing, and key lookups.\n",
    "try:\n",
    "    e = {'a':1,'aa':2}\n",
    "    x = e['b']\n",
    "except KeyError:\n",
    "    logging.error('Key error has been handled.')\n",
    "    print('Key error has been handled.')\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "    logging.error(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "57f967e1-bf66-4812-b0e1-be769ddb1499",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index error has been handled.\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    a = [1,2,3,4]\n",
    "    b = a[6]\n",
    "except IndexError:\n",
    "    logging.error('Index error has been handled')\n",
    "    print('Index error has been handled.')\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "    logging.error(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7eea73d6-9f9e-47ea-b41a-66cdbcaf9ef3",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "Ans->a) 'ImportError' arises when unknown,not installed or invalid module is imported inside the program.\n",
    "b) Sometimes it also occurs when the module is valid but the program is not able to find the module in current directory.\n",
    "c) 'ModuleNotFoundError' is a sublass of 'ImportError'.\n",
    "d) 'ModuleNotFoundError' is raised when Python cannot locate a module with the specified name or path. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "80bab1fa-6eae-48cf-9393-77136074662d",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "Ans->1) Always use specific errors in 'except' block which are likely to get trigger inside the try block.\n",
    "2) Use multiple except block to address all the error that could arise.\n",
    "3) Use Exception class at the end of all except block, to ensure that all errors will get handled.\n",
    "4) Use logging instead of print in order to handle the error as it will remain even after the execution of the program.\n",
    "5) Use finally block for execution important code that should be executed in any circumstances i.e closing files.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
